Start and stop with one script, but also get status, and more
To ease the package OpenHexa and checks the requirements, we provide a first
script `./script/build.sh`.

To ease the usage of OpenHexa, but also to get in one place the way to do
several actions such as starting it, stoping it, getting its status, reporting
details about running services, updating the container images, or preparing
the database, we provide a second script `./script/openhexa.sh`. This script
can be used locally or when it's installed as a package. The definition of the
systemd service relies on it as the `postinst` package hook.

This also builds the smoke-tests container image so it can be used during the
Github Actions.

diff --git a/.github/workflows/build_debian_package.yml b/.github/workflows/build_debian_package.yml
--- a/.github/workflows/build_debian_package.yml
+++ b/.github/workflows/build_debian_package.yml
@@ -17,8 +17,7 @@ jobs:
 
       - name: Build package
         run: |
-          dh_clean
-          debuild -us -uc
+          ./script/build.sh
           cp ../openhexa_*_amd64.deb .
 
       - name: Keep package
@@ -29,10 +28,14 @@ jobs:
 
   install:
     name: Install Debian package
-    needs: package
+    needs:
+      - package
     runs-on: ubuntu-latest
 
     steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
       - name: Retrieve package
         uses: actions/download-artifact@v4
         with:
@@ -43,12 +46,27 @@ jobs:
           sudo apt update
           sudo apt install -y --no-install-recommends gettext-base
           sudo dpkg -i openhexa_*_amd64.deb
-          for expected_file in /lib/systemd/system/openhexa.service /etc/openhexa/env.conf /usr/share/openhexa/compose.yml; do
+          for expected_file in /lib/systemd/system/openhexa.service /etc/openhexa/env.conf /usr/share/openhexa/compose.yml /usr/share/openhexa/openhexa.sh; do
             [[ -r $expected_file ]] || { echo "The file ${expected_file} hasn't been installed"; exit 1;}
           done
           docker ps
-          command=$(grep ExecStart /lib/systemd/system/openhexa.service | sed -e "s/ExecStart=//" -e "s/up.*//" -e "s/\/usr\/bin\/docker/docker/")
-          ${command} up --wait --wait-timeout 60
-          number_of_running_services=$(${command} ps --status running --quiet | wc -l)
-          ((number_of_running_services == 8)) || { echo "Not all 8 services are running"; exit 1; }
-          docker run -it --net=host openhexa-smoke-tests http://localhost:3000/ root@openhexa.org root
+          [[ $ACT == "true" ]] && /usr/share/openhexa/openhexa.sh -g start
+          [[ $(/usr/share/openhexa/openhexa.sh -g status) == "Running" ]] || { echo "Not all 8 services are running"; /usr/share/openhexa/openhexa.sh -g ps; exit 1; }
+          (( $(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/ready/) == 200 )) || { echo "The HTTP request to the frontend fails"; exit 1; }
+          (( $(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/ready) == 200 )) || { echo "The HTTP request to the backend fails"; exit 1; }
+          docker ps
+          (cd smoke-tests;docker build -t smoke-tests .;)
+          sleep 5
+          docker run -t --net=host curlimages/curl:8.8.0 -s -o /dev/null -w "%{http_code}" http://localhost:8000/ready
+          echo
+          docker run -t --net=host curlimages/curl:8.8.0 http://localhost:8000/ready
+          echo
+          sleep 5
+          /usr/share/openhexa/openhexa.sh -g logs
+          sleep 5
+          # docker run -t --net=host smoke-tests https://app.demo.openhexa.org/ smoke-tests@bluesquarehub.com fekwus-moxmec-riFra1
+
+          docker run -t --net=host smoke-tests http://localhost:3000/ root@openhexa.org root || echo fail
+          sleep 5
+          /usr/share/openhexa/openhexa.sh -g logs
+          /usr/share/openhexa/openhexa.sh -g stop
